### ISSUE TITLE
根据表达量进行层次聚类脚本缺失，cattle GTEx网站的下载的表达文件缺少样本与基因名信息

### ISSUE THREAD

**Issue by shengs-UCAS** [shuliliu/cattleGTEx#1]
你好！

非常感谢cattle GTEx课题研究的相关工作！但是最近我在使用时发现：
1.Gene_expression_quantification部分使用dendextend包根据基因表达数据进行层次聚类部分的脚本似乎没有提交。
2.cattle GTEx网站下载的Gene_expression_TPM_FarmGTEx_cattle_V0.txt.gz文件仅包含表达矩阵，而无行列名，缺少样本与基因名信息。

祝一切顺利！

**Comment by shuliliu** [comment]
We will re-upload the files soon. Once done, we will let you know.

**Comment by shuliliu** [comment]
Please download the gene expression matrices from https://figshare.com/articles/dataset/CattleGTEx-Gene_expression_data/21564780 in figshare.  And also we have update the codes for clustering.

**Comment by shengs-UCAS** [comment]
Thanks so much for your response!
